name: Testing

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  test:
    name: Test the Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t jljl1337/testpod:test .

      - name: Run and test the Docker image
        run: |
          docker run -d jljl1337/testpod:test
          docker exec $(docker ps -q) curl -s localhost:8000
          docker exec $(docker ps -q) curl -s localhost:8000/api
          docker stop $(docker ps -q)